{
 "title": "Market",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "symbol",
    "query": "SELECT DISTINCT symbol FROM spark_last_price_history ORDER BY symbol"
   },
   {
    "name": "date",
    "query": "SELECT \n    to_char(date, 'YYYY-MM-DD') as \"date_text\",\n    extract(epoch from date) * 1000 as \"date_value\"\nFROM (\n    SELECT DISTINCT date \n    FROM spark_daily_change_history \n    ORDER BY date DESC\n) dates;"
   },
   {
    "name": "week_market_cap",
    "query": "SELECT DISTINCT\n    to_char(week_start, 'YYYY-MM-DD') AS week_start_text\nFROM spark_marketcap_weekly_ranking\nORDER BY week_start_text DESC;\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-size: 26px; font-weight: bold;\">\r\n    Метрики для монеты '$symbol'\r\n</div>"
   }
  },
  {
   "title": "Историческая информация по '$symbol'",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "SELECT \r\n    symbol as \"Монета\",\r\n    avg_price as \"Средняя цена\",\r\n    min_price as \"Минимум\",\r\n    max_price as \"Максимум\"\r\nFROM spark_avg_price_history \r\nWHERE symbol = '$symbol'\r\nORDER BY avg_price DESC;"
    }
   ]
  },
  {
   "title": "Текущая цена '$symbol'",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "SELECT \r\n    symbol as \"Монета\",\r\n    price as \"Текущая цена\",\r\n    last_collected as \"Время обновления\"\r\nFROM spark_last_price_history \r\nWHERE symbol = '$symbol'\r\nORDER BY price DESC;"
    }
   ]
  },
  {
   "title": "Доля капитализации рынка",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "p30" ] } },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "SELECT\r\n    symbol,                       -- подпись секции на графике\r\n    market_dominance_pct AS value  -- доля рынка в процентах\r\nFROM spark_market_dominance_history\r\nWHERE analysis_timestamp = (\r\n    SELECT MAX(analysis_timestamp) FROM spark_market_dominance_history\r\n)\r\nORDER BY market_dominance_pct DESC;\r\n"
    }
   ]
  },
  {
   "title": "Динамика цены '$symbol'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "SELECT\r\n    date AS time,\r\n    end_price AS \"Daily Price\"\r\nFROM spark_daily_change_history\r\nWHERE symbol = '$symbol'\r\nORDER BY date ASC;\r\n"
    }
   ]
  },
  {
   "title": "Волатильность(по неделям) для '$symbol'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "SELECT\r\n    week AS time,\r\n    symbol AS metric,\r\n    volatility_pct\r\nFROM spark_weekly_volatility_history\r\nWHERE symbol = '$symbol'\r\nORDER BY week\r\n"
    }
   ]
  },
  {
   "title": "ИЗМЕНЕНИЕ ЦЕНЫ '$date'",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "WITH latest AS (\r\n    SELECT *,\r\n           ROW_NUMBER() OVER (PARTITION BY coin_id, date ORDER BY analysis_timestamp DESC) AS rn\r\n    FROM spark_daily_change_history\r\n    WHERE date = '$date'\r\n      AND price_change_pct IS NOT NULL\r\n)\r\nSELECT \r\n    symbol AS \"Монета\",\r\n    price_change_pct AS \"Изменение %\",\r\n    CASE \r\n        WHEN price_change_pct > 0 THEN 'Рост'\r\n        WHEN price_change_pct < 0 THEN 'Падение' \r\n        ELSE 'Без изменений'\r\n    END AS \"Тренд\"\r\nFROM latest\r\nWHERE rn = 1\r\nORDER BY price_change_pct DESC;\r\n"
    }
   ]
  },
  {
   "title": "Динамеческий рейтинг по капитализации",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "WITH weekly_top AS (\r\n    SELECT\r\n        week_start,\r\n        coin_id,\r\n        symbol,\r\n        weekly_market_cap,\r\n        rank_position\r\n    FROM spark_marketcap_weekly_ranking\r\n    WHERE rank_position <= 10\r\n      AND to_char(week_start, 'YYYY-MM-DD') = '$week_market_cap'\r\n),\r\nprevious_week AS (\r\n    SELECT\r\n        week_start + INTERVAL '7 DAY' AS week_start,\r\n        coin_id,\r\n        rank_position AS prev_rank\r\n    FROM spark_marketcap_weekly_ranking\r\n    WHERE rank_position <= 10\r\n)\r\nSELECT\r\n    to_char(w.week_start, 'YYYY-MM-DD') AS week_start_text,\r\n    w.symbol,\r\n    w.weekly_market_cap,\r\n    w.rank_position,\r\n    CASE\r\n        WHEN p.prev_rank IS NULL THEN 'new'\r\n        WHEN w.rank_position < p.prev_rank THEN CONCAT('↑', p.prev_rank - w.rank_position)\r\n        WHEN w.rank_position > p.prev_rank THEN CONCAT('↓', w.rank_position - p.prev_rank)\r\n        ELSE '–'\r\n    END AS rank_change\r\nFROM weekly_top w\r\nLEFT JOIN previous_week p\r\n    ON w.coin_id = p.coin_id\r\n    AND w.week_start = p.week_start\r\nORDER BY w.rank_position ASC;\r\n"
    }
   ]
  },
  {
   "title": "Динамический рейтинг по объёму торгов",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "cryptodb",
     "rawSql": "WITH weekly_top AS (\r\n    SELECT\r\n        week_start,\r\n        coin_id,\r\n        symbol,\r\n        weekly_volume,\r\n        rank_position\r\n    FROM spark_volume_weekly_ranking\r\n    WHERE rank_position <= 10\r\n      AND to_char(week_start, 'YYYY-MM-DD') = '$week_market_cap'\r\n),\r\nprevious_week AS (\r\n    SELECT\r\n        week_start + INTERVAL '7 DAY' AS week_start,\r\n        coin_id,\r\n        rank_position AS prev_rank\r\n    FROM spark_volume_weekly_ranking\r\n    WHERE rank_position <= 10\r\n)\r\nSELECT\r\n    to_char(w.week_start, 'YYYY-MM-DD') AS week_start_text,\r\n    w.symbol,\r\n    w.weekly_volume,\r\n    w.rank_position,\r\n    CASE\r\n        WHEN p.prev_rank IS NULL THEN 'new'\r\n        WHEN w.rank_position < p.prev_rank THEN CONCAT('↑', p.prev_rank - w.rank_position)\r\n        WHEN w.rank_position > p.prev_rank THEN CONCAT('↓', w.rank_position - p.prev_rank)\r\n        ELSE '–'\r\n    END AS rank_change\r\nFROM weekly_top w\r\nLEFT JOIN previous_week p\r\n    ON w.coin_id = p.coin_id\r\n    AND w.week_start = p.week_start\r\nORDER BY w.rank_position ASC;\r\n"
    }
   ]
  }
 ]
}